/// Firebase config template. Replace with the file generated by
///   `flutterfire configure --project=aquai-prod`
/// before shipping. Keep the real `firebase_options.dart` out of git.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey:            'REPLACE_ME',
        appId:             'REPLACE_ME',
        messagingSenderId: 'REPLACE_ME',
        projectId:         'aquai-prod',
        storageBucket:     'aquai-prod.appspot.com',
      );
}
